name: Build and Release APK

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: temurin

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4' 
          channel: 'stable'
          cache: false

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build Appbundle
        run: flutter build appbundle --release

      - name: Rename APK with Custom Name
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Manipalv3.1.1-${{ github.run_number }}.apk

      - name: Rename Appbundle with Custom Name
        run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/Manipalv3.1.1-${{ github.run_number }}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/Manipalv3.1.1-${{ github.run_number }}.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/Manipalv3.1.1-${{ github.run_number }}.aab

  release:
    name: Release APK and AAB
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab

      - name: Create APK Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Manipalv3.1.1-${{ github.run_number }}.apk
          token: ${{ secrets.GH_TOKEN }}
          tag: v3.1.1-${{ github.run_number }}
          name: APK Release v3.1.1-${{ github.run_number }}
          body: "MANIPAL"
          draft: false
          prerelease: false
          replaceExisting: true

      - name: Create AAB Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: Manipalv3.1.1-${{ github.run_number }}.aab
          token: ${{ secrets.GH_TOKEN }}
          tag: v3.1.2-${{ github.run_number }}
          name: AAB Release v3.1.1-${{ github.run_number }}
          body: "MANIPAL"
          draft: false
          prerelease: false
          replaceExisting: true
          skipIfReleaseExists: true
